conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.5

data:
  name: coloradar
  root: "/scratch/project/cpautodriving/yanlongyang/coloradar_kitti_format/processed"

# data:
#   name: DatasetRADIal
#   root: "/scratch/user/yanlongyang/Project1_Diffusion_related/dataset_with_labels/radialx_infos_train.pkl"


measurement:
  operator:
    name: radar_imaging
    num_antennas: 84
    shape: [64, 128]
    # intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.01
