conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.5

data:
  name: DatasetRADIal
  # root: "/scratch/project/cpautodriving/yanlongyang/dataset_with_labels/radialx_infos_train.pkl"
  root: "/scratch/project/cpautodriving/yanlongyang/dataset_with_labels/radialx_countryside_dataset.pkl"
  RBINS: 512
  ABINS: 768
  M: 0


measurement:
  operator:
    name: radar_imaging
    num_antennas: 84
    shape: [512, 768]
    # shape: [256, 384]
    # shape: [128, 192]
    # intensity: 3.0
  
  noise: 
    name: gaussian
    sigma: 0.01

# constraint:
#   method: taming.models.vqgan.VQModel
#   model_path: '/scratch/user/yanlongyang/Project1_Diffusion_related/Object_Detection_with_Super_Resolution_Radar_Point_Cloud_Creation_using_Deep_Learning/stable-diffusion-main/logs/2024-09-07T01-22-16_vqvae_32x48x4_radial/checkpoints/last.ckpt'
  # params:
  #   in_channels: 3
  #   out_channels: 3