conditioning:
  main_sampler: resample
  method: ps # Do not touch
  params:
    scale: 0.5

data:
  name: DatasetRADIal
  root: "demo"
  RBINS: 512
  ABINS: 768
  M: 0


measurement:
  operator:
    name: radar_imaging
    num_antennas: 84
    shape: [512, 768]
  
  noise: 
    name: gaussian
    sigma: 0.01
